# Generated by Django 4.2 on 2026-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_note_is_archived_note_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
