# Generated by Django 6.0.5 on 2026-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_note_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
