# Generated by Django 6.0.5 on 2026-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_note_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
