# Generated by Django 4.2 on 2026-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
